#!/bin/bash
# Скрипт показа информации о проекте ProzorroHunter

clear

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║   🎯  ProzorroHunter — TenderFlow                               ║"
echo "║   Автоматический 24/7 трекер тендеров Prozorro                  ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ ПРОЕКТ ПОЛНОСТЬЮ ГОТОВ К ИСПОЛЬЗОВАНИЮ!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📂 СТРУКТУРА ПРОЕКТА"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 Корневая директория:"
ls -lh | grep -E "^-|^d" | awk '{printf "   %-30s %6s\n", $9, $5}'
echo ""
echo "📁 Backend (backend/):"
ls -lh backend/ | grep "^-" | awk '{printf "   %-30s %6s\n", $9, $5}'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ ОСНОВНЫЕ ВОЗМОЖНОСТИ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✅ Backend на FastAPI с REST API"
echo "  ✅ PostgreSQL + SQLAlchemy для хранения данных"
echo "  ✅ Celery + Redis для фоновых задач 24/7"
echo "  ✅ Автоматический мониторинг каждые 10 минут"
echo "  ✅ Telegram бот на aiogram 3.x"
echo "  ✅ Docker & Docker Compose"
echo "  ✅ Готовность к деплою (Render/Railway/Heroku)"
echo "  ✅ Полная документация"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 ДОКУМЕНТАЦИЯ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ⭐ START_HERE.md              - Начните отсюда!"
echo "  📋 QUICKSTART.md              - Пошаговая инструкция"
echo "  📄 FILES_MAP.md               - Карта всех файлов"
echo "  🌐 DEPLOYMENT.md              - Инструкции по деплою"
echo "  📝 COMMIT_INSTRUCTIONS.md     - Работа с GitHub"
echo "  📖 README.md                  - Основная документация"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 БЫСТРЫЙ СТАРТ — 5 ШАГОВ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1️⃣  Получить Telegram Bot Token у @BotFather"
echo "  2️⃣  Создать .env файл: cp .env.example .env"
echo "  3️⃣  Вставить токен в .env"
echo "  4️⃣  Запустить: ./init.sh (или docker-compose up -d)"
echo "  5️⃣  Протестировать бота в Telegram"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🐳 DOCKER КОМАНДЫ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Запуск:           docker-compose up -d"
echo "  Остановка:        docker-compose down"
echo "  Статус:           docker-compose ps"
echo "  Логи:             docker-compose logs -f"
echo "  Перезапуск:       docker-compose restart"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 ПОЛЕЗНЫЕ ССЫЛКИ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  API Docs:         http://localhost:8000/docs"
echo "  Health Check:     http://localhost:8000/health"
echo "  PostgreSQL:       localhost:5432"
echo "  Redis:            localhost:6379"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 СТАТИСТИКА"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Файлов создано:   19"
echo "  Строк кода:       ~2,500"
echo "  Размер проекта:   ~75 KB"
echo "  Сервисов:         6 (postgres, redis, api, worker, beat, bot)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 СЛЕДУЮЩИЕ ШАГИ:"
echo ""
echo "   1. Прочитайте START_HERE.md для полной инструкции:"
echo "      cat START_HERE.md"
echo ""
echo "   2. Или следуйте QUICKSTART.md пошагово:"
echo "      cat QUICKSTART.md"
echo ""
echo "   3. Запустите локально:"
echo "      ./init.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 Готовы начать? Выполните: ./init.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
